### ISSUE TITLE
Grammarly Privacy Concerns

### ISSUE THREAD

**Issue by ghost** [jcs-elpa/flymake-grammarly#2]
Just for the record Grammarly has important privacy issues from their privacy policy/terms of service.

https://old.reddit.com/r/privacy/comments/b0y95z/why_i_removed_grammarly_chrome_extension_and/
https://garymcgath.com/wp/privacy-security-grammarly/
https://www.youtube.com/watch?v=rgUGJDMSG1E

**Comment by jcs090218** [comment]
I will close this issue now since I have already pinned this issue! Thanks!
