### ISSUE TITLE
does not work on some files

### ISSUE THREAD

**Issue by vzaliva** [jcs-elpa/flymake-grammarly#4]
I have flymake-grammarly working on a small text file. However, on a larger file, it does not. There are no errors in the log buffer.
I can have Reporting backends: flymake-grammarly--checker. How can I fix/diagnose this?

**Comment by jcs090218** [comment]
I think this may related to this https://github.com/emacs-grammarly/flycheck-grammarly/issues/3?

Can you post the content you are trying to diagnose here? Thanks!

**Comment by jcs090218** [comment]
The issue should be fixed in 28888bc8d1c795e1b2d798fb5c6cdcc16571c73e.

Feel free to reopen this if it does not work!
