### ISSUE TITLE
Make narrowed buffers work

### ISSUE THREAD

**Issue by rudolf-adamkovic** [jcs-elpa/flymake-grammarly#7]
Narrowing a buffer (e.g. `C-x n s` in `org-mode`) makes `flymake-grammarly` show its highlights in incorrect places.

**Comment by jcs090218** [comment]
Just made a patch in #9. Can you check to see if this work? Thanks!

**Comment by jcs090218** [comment]
Closing this issue now. Feel free to reopen or open up another issue if the issue persists.

**Comment by rudolf-adamkovic** [comment]
_Note:_ My apologies for not replying sooner.  I have stopped using the Grammarly service for now.

**Comment by jcs090218** [comment]
No problem! Thank you for your reply! ❤️ 👍
